// 単語とジャンルのリスト
const wordDataList = [
    { word: "えくれあ", genre: "たべもの" },
    { word: "ぴすとる", genre: "ぶき" },
    { word: "きりたんぽ", genre: "たべもの" },
    { word: "おかりな", genre: "がっき" },
    { word: "おおさんしょうお", genre: "いきもの" },
    { word: "きっちんたいまー", genre: "どうぐ" },
    { word: "ろうがんきょう", genre: "どうぐ" },
    { word: "さがわきゅうびん", genre: "きぎょう" },
    { word: "どくたーぺっぱー", genre: "のみもの" },
    { word: "ふくしま", genre: "けん" },
    { word: "たらこすぱげてぃ", genre: "たべもの" },
    { word: "といすとーりー", genre: "えいが" },
    { word: "すぺありぶ", genre: "たべもの" },
    { word: "いたりあ", genre: "くに" },
    { word: "りんご", genre: "たべもの" },
    { word: "らいおん", genre: "いきもの" },
    { word: "ふらんす", genre: "くに" },
    { word: "えんぴつ", genre: "どうぐ" },
    { word: "ぎたー", genre: "がっき" },
    { word: "あおもり", genre: "けん" },
    { word: "こーら", genre: "のみもの" },
    { word: "かたな", genre: "ぶき" },
    { word: "となりのととろ", genre: "えいが" },
    { word: "にんてんどう", genre: "きぎょう" },
    { word: "おむらいす", genre: "たべもの" },
    { word: "めだか", genre: "いきもの" },
    { word: "てれび", genre: "かでん" },
    { word: "ぴあの", genre: "がっき" },
    { word: "どいつ", genre: "くに" }
];
